{{- if .Values.thanosObjectStorageConfigSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.thanosObjectStorageConfigSecret.name }}
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
type: Opaque
stringData:
  {{ .Values.thanosObjectStorageConfigSecret.secretConfigFilename }}: |-
    type: {{ .Values.thanosObjectStorageConfigSecret.type }}
    config:
      bucket: {{ .Values.thanosObjectStorageConfigSecret.config.bucket }}
      endpoint: {{ .Values.thanosObjectStorageConfigSecret.config.endpoint }}
      region: {{ .Values.thanosObjectStorageConfigSecret.config.region }}
      part_size: {{ .Values.thanosObjectStorageConfigSecret.config.part_size }}
{{ - end -}}
