# certs:
#   server:
#     key: |
#       -----BEGIN RSA PRIVATE KEY-----
#       MIIJKgIBAAKCAgEAzurP1Y4zZ6NfSd3eZFadEAxX0gdBSXOSfvwtNswlKt+3zkfz
#       y5M6KS5GcXoV5xRfxhb52QxBPM3z91t6hizxf9/eY/ZtG38pQIQpyyrEJi5A2jx1
#       QVFnpFYPxdAKTOTgjvb3IbDH1RNOeGv2OPY/Pn2Pek1KjU4/CvNWDuJvOUeYdin1
#       EgwYAzApoUrmJum7D1w61iXsQmBXXTVWNo1m+xiNLzp3lopXSuh1nF3xNIogdbnM
#       nEo0dIzweLrtzTbG+U1gilgoEYX8hXTbch5f81ihn6koQOMhBPRTCwm0rDhb8lO4
#       c/jdGlZUOn63pDeoElk1agIG1QffEG6WkT3jxA1rip8RMDdqPXI6tDz2K06HDjBR
#       2o2EGK3FEBkuCYwQD1KJpJkPBBvnuCU2aV8NztquYTC/fHXWYIsVWNS6BVH4InaF
#       Dp7sDpbAZF/nCxUhdqM5fMD3f1uvCd8iJK+WK+b8Rj5C8RJxAHxatGtn7cFrei8L
#       lH3gfR1SF8wUBP7UscNy8eDfI/n5YCuYIh+Z1OJyygwcI2YL7mbY0ZKFDeamCOVO
#       cFMmX6PKpHnIq7fk37KbN7GK0m9srnoLjXofLI6QdaSI+r8gtfVOjS4xin3dtOAX
#       uMDssOijWq6ml0JSPL6LhFO8yuDyCNUWYsXbPUzh/S5jIn2xupeKPwI8ODMCAwEA
#       AQKCAgA5GVkTAHO1BMNV2fD11WTwOce+QJxGjar+ec5sUbdr9mJ9fSOMqOsi1A9C
#       X0NOCjRHsK1vtM8H3XmWZ9sOzbYy6G8xPJ5tOREEKbRyyTFpq9ffoVFmHfWwxsMB
#       fmBpSbuiGAqodGUgqnw8BObkXyeisfl28X9CMTZ6ah30a43vy48KBJgJS+cQcij6
#       xnVuhY9GNNhTohFpW7agFQjecvTZE7RaNRMtKq3eEPnrlYzrR7afZg9Njbid9Qqi
#       9kqLF7OetjiO1Lbx5vyBQ3cPLcyilXG8YmymQ0coW9fSsvH1mHPfEjVTY3h4PRxv
#       K+q3WVh6/70arMZ/4PUwTqQkHmUMhHGZ/+LqdzyQ7RINgEIIvB8Yge+VZXniALDT
#       P0TdXDdJc43TtdXSiedYeke8OM+Nqrk67YSWyhXiFXqkwpYLxeIlSaJbeKW9KJsm
#       Nwat7orCgyF36W0gCMZAYQtbpV+FG6YILLpYRizDQsozOjVi+O/rxln4gYZMsEg6
#       iCibOxWXXPVEwyWjRcwkafdAMCL+9SEQYFWNmLBqTz19WUYVtsA2ezI31PD05GqT
#       N74uwiy6MmAOWw60P8iEnVxv6aLsq3NPi/Y0rfIRjxwJhgm5lJkgpJVEWMsBh9BM
#       OSuWpznbs1uZ0XHdjhZojjBkopEC5alynzbPXi7LAO/kMqGYGQKCAQEA+9Jeb6JZ
#       STlu1SkZQ+6pOI/lBwt46xopLQNgdaAGqwomJwSkZAFPh86Q0U757GXEd2WTvIzr
#       D+PJ3uz4B7E8NsBZYLdSu1yAAVifbJqjbfclzD1vXIFbHG84O4YNsN2qFMxLnTUA
#       XvQBdusnNjmvNNcub/gzYNELQNE26ultz10V2j8gqm/uzWo9hqR00+7e286M3Pzf
#       guOC7bxhCGH8YRvUdPB4kic1KD78m0BfarZI1bYSHKndDgkH8F+199LwZ6w+i8JR
#       NeTviL2PcLF0lum6hahRN8BuyEw3FegklVw+Z2TX6k8JXkunMj1fPMav0lxDsxcN
#       DRRPpgEoWfmbxwKCAQEA0lm1MDLUdxnb4d08jVBAsy1wEKhNt4s44/W8fZpCyhUM
#       MVG9jenYMoNBxnmDALyzXu0NZbWSVkvg129ALwVFG8HIqeNZA3bJrWwz11Q0gahs
#       3nV5/nUSy38pe7H+GXjX9EHm+H+/25Nl4Wr+Sg0XAjKkWu4U+phA48CNTPxlZCRT
#       nJWmJWZayvrwj6N8CyUe4GhXJ08yPw3vZFV2mfiA3sMibXDvg2GiE3uUlcviBJJ6
#       ghlTzBkYKt20693K0yCW8G+eDyPEajyeBamZMYrn2aMP+P2nHvXIqV3rQGrDjETX
#       CsOutFCuRhufDD/XSU0YyUrKq8mTu/nSSBU9LklINQKCAQEAwgEuVB7lXq5qnrpN
#       BrMFl9f0AFtsSuQauN0TIUuqF3d4MTM4WvtPhDc2BqsrjF5S4BFXojmGlvVM/vvd
#       kj+PPjcuJH7XtBTtYRwfppH0OrHfYtwpwUC/Ksbcsa7zOUFs2R0TXAgLQxwFTNKZ
#       oQML4k+tLQIwwvQKEWOdRZmUyd7TCRL9XZFijsq8n9BvWR98fidBCreekr4ojnNE
#       5ipnP4ErSvRAT4j5QQpVnl4XpKTOtCbTCVYsQbXfceaq0ESohZaDkTShUD4R9Gzl
#       51IvmlxzIKmt+J++OX3OKohwNsmcIhfk6FT/yK/MHb5+cto3dn8ygPTPTzZIroHR
#       zo+o3QKCAQEAiyDgka+dDeWhpMOi8EjbcmekTrAzLyo7h7OaZ20nree798b73CiG
#       YeqlD7SBLHSjIy8hhFtTHhbz8SpZRoBy1EgZBB0mW/8up7EAnPTKAdQ3pfAHr4EZ
#       3FUQSAtTaN+f3qPUNBqy+HWGllEhPjNoO4Dpamc8ov8fNETAcOIj4deRIeltSiFn
#       /gd6I1dbjTeRM5ZvxsVAE6qQ40kPuAlAm5ZvZ/mhwcFK5R4BCg8fQCzuMKy12zHh
#       5UBdEQDSzVAp5X++CH98w1OypUYm2Djq3u1WfDaxWe3xOeyv1ByJmHZT0X/aRtNy
#       YVaVnRGAwK/orAL3CCa8u0Eij6DUpY+83QKCAQEAnBnc7/cLmo5dW8yTIQ33H904
#       Rq7JH2J5p5+JtBQ2E0sWChWC5csH119Y+s1fmHQ79mqXeFRd1xgSMiJjAVGy4Z/+
#       xO4n88GYung8EvvUooBrx8JhjXOB9E5wTeygdQrDfKku1vZRxRb1z8QOcBYvPVjW
#       /KQ6g+NXOUjD4VqUgsNl30WXbDBXZ6BLt1OC/6dDaWQ/JzE6o0eI3uxsfyA87bNW
#       Q2tQ0SBkntyXSV5YC5vOuMWKHqz+He0TEv1KGGoyIS/JFldhMX2p68x2HO6rg9Ez
#       lgjvPWZI415yjsEqPjLpDl2TwLBT8c5UMq8/Vij3hY8nSDldobDkK1Gx6aVAzw==
#       -----END RSA PRIVATE KEY-----
#     crt: |
#       -----BEGIN CERTIFICATE-----
#       MIIFOjCCAyICAQEwDQYJKoZIhvcNAQEFBQAwYTELMAkGA1UEBhMCU1AxDjAMBgNV
#       BAgMBUl0YWx5MRIwEAYDVQQHDAlPcm5hdmFzc28xDTALBgNVBAoMBFRlc3QxDTAL
#       BgNVBAsMBFRlc3QxEDAOBgNVBAMMB1Jvb3QgQ0EwHhcNMjIwNzEyMTYzNjUwWhcN
#       MjMwNzEyMTYzNjUwWjBlMQswCQYDVQQGEwJTUDEOMAwGA1UECAwFSXRhbHkxEjAQ
#       BgNVBAcMCU9ybmF2YXNzbzENMAsGA1UECgwEVGVzdDEPMA0GA1UECwwGU2VydmVy
#       MRIwEAYDVQQDDAlsb2NhbGhvc3QwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIK
#       AoICAQDO6s/VjjNno19J3d5kVp0QDFfSB0FJc5J+/C02zCUq37fOR/PLkzopLkZx
#       ehXnFF/GFvnZDEE8zfP3W3qGLPF/395j9m0bfylAhCnLKsQmLkDaPHVBUWekVg/F
#       0ApM5OCO9vchsMfVE054a/Y49j8+fY96TUqNTj8K81YO4m85R5h2KfUSDBgDMCmh
#       SuYm6bsPXDrWJexCYFddNVY2jWb7GI0vOneWildK6HWcXfE0iiB1ucycSjR0jPB4
#       uu3NNsb5TWCKWCgRhfyFdNtyHl/zWKGfqShA4yEE9FMLCbSsOFvyU7hz+N0aVlQ6
#       frekN6gSWTVqAgbVB98QbpaRPePEDWuKnxEwN2o9cjq0PPYrTocOMFHajYQYrcUQ
#       GS4JjBAPUomkmQ8EG+e4JTZpXw3O2q5hML98ddZgixVY1LoFUfgidoUOnuwOlsBk
#       X+cLFSF2ozl8wPd/W68J3yIkr5Yr5vxGPkLxEnEAfFq0a2ftwWt6LwuUfeB9HVIX
#       zBQE/tSxw3Lx4N8j+flgK5giH5nU4nLKDBwjZgvuZtjRkoUN5qYI5U5wUyZfo8qk
#       ecirt+Tfsps3sYrSb2yueguNeh8sjpB1pIj6vyC19U6NLjGKfd204Be4wOyw6KNa
#       rqaXQlI8vouEU7zK4PII1RZixds9TOH9LmMifbG6l4o/Ajw4MwIDAQABMA0GCSqG
#       SIb3DQEBBQUAA4ICAQB7vN8eIvqya9Sa1OtgBN3IyfEU2LHWudQ9izd+Ll46JaAI
#       YzUA7/n+7uq7smiRmVnvTAjpD1gSDw0BEmClhD+qbIRoeys+GmYqX8aUVvsPzTf4
#       ihKa9Ihg96ffnGB53WurOGV7lQgWyyhrX04hB5F97KZGaIH4+HnWaF/v1t45i0sE
#       8F2UvoTLd2OKLHeYqPB7Neql64vhJnG0dy7OlrVWzODs+knYvDA8tGDJ3pQc2U77
#       2yTM+i0sXgwEdILfFyzDhnhTIPpH4KBCjSxlPioBh9MEYJqys2S/QBTunfuXtPhg
#       liz/eohTfn0L0RIrjKygRsm9MphyI9WVFUuz1ZOfmequDUpVpkh24J/sXR6VFdYA
#       e9qB7Dj30QcCr7Gl1eYJ8IYvyCnspllDVvQVH6oS2PtGOkLeH9jP7Yz601NZJPQe
#       3cqvmPc3RhUwrXrewl5UOrko/iEq7U5Mhr35+BZx14XMHot7/iwHoGoqSdBDmrGf
#       lJ9ZYMs6kcsN4voeoGZ6tLtO/JUE5XWB7dGFB2ZC+eYVCIwS4nkE9gV9MAlFNuiM
#       ATqJ5+KGMVr56PgvTwfkLa3ftmXtUDHAUMf6yfL9MZd+0GCycRwDkQrerWF1eHC0
#       cUMUvazUv07PqHlv2hUxJYrKn2aF4TLcj27yNLGQ5caNHf0Bo5IRHZ3Oq5vAtg==
#       -----END CERTIFICATE-----
#   ca:
#     crt: |
#       -----BEGIN CERTIFICATE-----
#       MIIFPjCCAyYCCQD1Crivd9MP6DANBgkqhkiG9w0BAQsFADBhMQswCQYDVQQGEwJT
#       UDEOMAwGA1UECAwFSXRhbHkxEjAQBgNVBAcMCU9ybmF2YXNzbzENMAsGA1UECgwE
#       VGVzdDENMAsGA1UECwwEVGVzdDEQMA4GA1UEAwwHUm9vdCBDQTAeFw0yMjA3MTIx
#       NjM0MjNaFw0yMzA3MTIxNjM0MjNaMGExCzAJBgNVBAYTAlNQMQ4wDAYDVQQIDAVJ
#       dGFseTESMBAGA1UEBwwJT3JuYXZhc3NvMQ0wCwYDVQQKDARUZXN0MQ0wCwYDVQQL
#       DARUZXN0MRAwDgYDVQQDDAdSb290IENBMIICIjANBgkqhkiG9w0BAQEFAAOCAg8A
#       MIICCgKCAgEAvleMTf7RKytnp/5005m2eKTDcXZqtuGgcueyD+FQZPWe0nR8QrsA
#       MxZiLCf3NIdTVfm/nyDCNkbchw481XwWfLhZOlRoxVBhz9PaPBMl1/zUwAHkdX8P
#       BlQgxzr707UIqvfDjqpcd2mZq57De2ClOBBdRoSqBsT5Lm2yfQPPjVx/lDw8ZmoW
#       6BECw4d21Xs4WIut39jWGqGViqRD2e+AW6CX3VeJOAjwzDaZHJsXfjHEv5cz6V58
#       70yuJKX+M8sYsVt0FKJvBmCOr3pUjHCx5Uxhx1MM6EgO8ddD5PLO800VWiHCJZyy
#       /s9A98/hJjSIKHtMj84vqXUwTtOAxjanxyXlxpL1kMGcFPbAsP230ctuTwGrBI2S
#       MtGv2ZLnrzD4EX9vNOLRA+TTqR7k1XkDA6QVOwlbijWNa4E21cXGD1UhDA1JrgcF
#       8/xxoDMn/BXv2PoEcpzc7YP6dXprkhPAoExBcHV9rPYTBXfxW31+EgbGs/ZxZJdR
#       u+U32Gts2DvHMYW4hTkJLwGtBrO+aWBxRflN4KWlG6YmWMxA3SHK8MpWXeIetEt9
#       NOQlTeH7Kj6jaX/px7qEmIkVDcVakb4i9F/FDJ5z1guYEGwwwoWSfhTg9swxB98k
#       0MrhjGwMnkPcgwVGeepNUZPfvQhfU+LptJKUh+lMHESaeHXS9x/9r+8CAwEAATAN
#       BgkqhkiG9w0BAQsFAAOCAgEAkHQluEVtcmEoSY7vuq1S5AK24m/o44x6wdlmkg/r
#       tNB/3bBQ1vyEqB8EDCL75SWyBXftvI3pQBOEMbNK5op/mQbx3Dt3llfUn+vy5v4Y
#       ggGVuB81TYhwPN7pZzm28hsf6Aj4pFw7/erxQnRu0V0jtL07VN6ZBrnDuRE4PJJF
#       5xFhz//TfavxVTim2Ck5hqoEiwk1rBYkdbtPc5iolNDrDDmM4sv1Lo9+5uo0M4Sw
#       y/6Mnkt44AZyV4PHJZzcmCZULcAC9FPRN81r1cTquF1p44k1mRG7bLIfw4fA9FBg
#       nIPgpuhrXaNihkF79Tn0j3wRvOZLRCKlukjiy25JSqmLX0aR3WPdRYHl61wfH9Yx
#       wue9ZL/v4YVcd2+w0sDFu2slFh0274l1JuuV89AgFl0HKaB28qo4hakZzqWGl16/
#       U8GufQp69zLm8e3DN7BDHvCWQnOVPpgTF/P8Sv6ZiaAiA+tWlpNn/G/RNbzwF1+Q
#       uHMwYAcY85BTwsn82sfM55pTgcVzEHjAbehsQG+xBpONt9ipS05m474t8JcO+Yxr
#       aHQtl8XgVVV+FkdjUAIpjyrWE9/Ij/pMF6wZuwjncpHWRjKGDZ4BKgqO90fitdFm
#       8V9/KDvL1nK8cjbM7m04DMPuHhRuaq9O1lY5sshBFRAbEapv+N6h+xWB/HZeVoFC
#       F94=
#       -----END CERTIFICATE-----

falco:
  grpc:
    enabled: true
  grpcOutput:
    enabled: true
