apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret_config_name }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  thanos-storage-config.yaml: |-
    type: s3
    config:
      bucket: {{ .Values.bucket_name }}
      endpoint: {{ .Values.endpoint }}
      region: {{ .Values.region }}