apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret_config_name }}
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
type: Opaque
stringData:
  thanos-storage-config.yaml: |-
    type: s3
    config:
      bucket: {{ .Values.bucket }}
      endpoint: {{ .Values.endpoint }}
      region: {{ .Values.region }}
